package com.artistlink.post;

public enum PostType {
    ACHIEVEMENT, PERFORMANCE_CLIP, EVENT_PHOTO, ANNOUNCEMENT,
    UPCOMING_EVENT, VENUE_UPDATE, ARTIST_SPOTLIGHT, VENUE_ACHIEVEMENT,
    GENERAL
}
